apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: lvm-cluster
spec:
  upstream:
    repo: ocp-infra-packages
    package: clean-disk-job 
    revision: main
  targets:
  - objectSelector:
      apiVersion: infra.nephio.org/v1alpha1
      #apiVersion: cluster.open-cluster-management.io/v1
      kind: WorkloadCluster
      #kind: ManagedCluster
      matchLabels:
        nephio.org/site-type: edge
        #common: "true"
    template:
      downstream:
#        repo: target.name
        package: clean-disk-job
      annotations:
        approval.nephio.org/policy: initial
      injectors:
      - nameExpr: target.name
