apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: ocp-infra-packages
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /
    repo: https://github.com/Chanoian/infra-kpt-packages.git
  type: git